interface TypeFilters {
  codigo_reservacion?: string | null;
  client?: string | null;
  traveler?: string | null;
   hotel?: string | null;
  nombre?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  recordCount?: string | null;
  empresa?: string | null;
  status?: "Confirmada" | "Pendiente" | "Cancelada" | "Todos" | null;
  reservationStage?: "Reservado" | "In house" | "Check-out" | null;
  paymentMethod?: "Credito" | "Contado" | null;
  filterType?: "Check-in" | "Check-out" | "Transaccion" | "Creacion" | null;
  active?: "Activo" | "Inactivo" | null;
  hay_convenio?: "SI" | "NO";
  tipo_negociacion ?: string | null;
  estado ?: string | null;
  ciudad ?: string | null;
  precioMin ?: number | null;
  precioMax ?: number | null;
  costoMin ?: number | null;
  costoMax ?: number | null;
  incluye_desayuno?: boolean | "SI" | "NO" | null; 
  acepta_mascotas ?: "SI" |"NO";
  tiene_transportacion ?:"SI" | "NO";
  tipo_pago ?: "CREDITO" | "PREPAGO";
  rfc ?: string | null;
  razon_social ?: string | null;
  tipo_hospedaje ?: string | null;
  correo ?: string | null;
  infoCompleta ?: string| null;
  activo ?: boolean |"ACTIVO" | "INACTIVO" |null;
  reservante?: "Operaciones" | "Cliente";
  markUp?: number;
  id_client?: string | null;
  statusPagoProveedor?: null | string;
  markup_start?: null | number;
  markup_end?: null | number;
}
